### PR TITLE
CPU Speed Reporting Fix

### PR DESCRIPTION
**Pull request by Rucknar**
Merge to resolve an issue where the currently running clock speed is shown instead of the CPU's 'normal' speed. https://github.com/rancher/rancher/issues/2365

### CODE REVIEW

**Comment by vincent99** [comment]
Comments in https://github.com/rancher/rancher/issues/2365#issuecomment-149336470 , then please squash into 1 commit.

**Comment by cloudnautique** [comment]
@Rucknar, thank you for taking a pass at this. It looks like coverage is now missing for the cpu MHz case. Can you please add a test that verifies if X.XXGHz  is not in model name that it still falls back. I think you can create a new method that replaces the model name from cpuinfo_data() in the test file. Replace it with something AMD or ARM cpu like(They both do not include clock speed info). Then you'll need a new fixture, I'd copy the no_cadvisor_host_data fixture and change the CpuCollector patch to call the new method.. then write a test like `test_collect_data_cpuinfo`.

All the methods and test cases referenced above can be found here:
[Tests](https://github.com/rancher/python-agent/blob/master/tests/test_host_info_plugin.py)

**Comment by Rucknar** [comment]
@cloudnautique Not sure i follow requiring a 'method' as well as fixture and test.
I've had a go but the test fails as the fixture can't correctly address the info it requires, i've gotten somewhat confused and spent way too much time looking at what might be wrong. I'll not push but i've basically added: 

```
@pytest.fixture()
def no_frequency_in_model_name(mocker):
    mocker.patch.object(CpuCollector, 'model name', return_value='AMD Duron(tm) processor')

    host = HostInfo()
    data = host.collect_data()

    return data
```

```
def test_collect_data_cpuinfo(host_data):
    expected_cpuinfo_keys = ['modelName',
                             'count',
                             'mhz',
                             'loadAvg',
                             'cpuCoresPercentages'
                             ]

    assert sorted(host_data['cpuInfo']) == sorted(expected_cpuinfo_keys)

    assert host_data['cpuInfo']['modelName'] == \
        "Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz"
    
    assert host_data['cpuInfo']['mhz'] == 1700

def test_collect_data_cpu_frequency_fallback(no_frequency_in_model_name):

    assert no_frequency_in_model_name['cpuInfo']['mhz'] == 2334.915
```

I've tried several different ways of cutting it but i just think i'm not familiar enough with python or mock testing to 'get it'. Care to point out the error of my ways?

Thanks

Ed

**Comment by cloudnautique** [comment]
Hi Ed, 

This area of the code is kind of a pain to test since it is parsing a bunch of different sources. Really appreciate you digging in to this. 

Heres what I think we need, I haven't tested this personally, but it should roughly work. 

A new method to prepare the data (this method should work)
```
def non_intel_cpuinfo_data():
   d = cpuinfo_data()
   
  for line in d:
      if line.startswith("model name"):
         d[d.index(line)] = "model name : AMD Opteron 250\n"
  
  return d
 ```

A new fixture (I expect this to work)
```
@pytest.fixture()
def no_cadvisor_non_intel_cpuinfo_mock(mocker):
    mocker.patch.object(platform, 'system', return_value='Linux')
    mocker.patch('os.getloadavg',
                 return_value=(1.60693359375, 1.73193359375, 1.79248046875))

    mocker.patch.object(CpuCollector,
                        '_get_cpuinfo_data',
                        return_value=non_intel_cpuinfo_data())

    mocker.patch.object(MemoryCollector,
                        '_get_meminfo_data',
                        return_value=meminfo_data())

    mocker.patch.object(CadvisorAPIClient, '_get',
                        return_value=None)

    host = HostInfo()
    data = host.collect_data()

    return data
```

Then your test method should work...
```
def test_collect_data_cpu_frequency_fallback(no_cadvisor_non_intel_cpuinfo_mock):

    assert no_frequency_in_model_name['cpuInfo']['mhz'] == 2334.915

```

Thanks!

**Comment by Rucknar** [comment]
@cloudnautique Thanks a lot for the pointers. After a few white space crimes it's now updated and passed the drone testing.

**Comment by cloudnautique** [comment]
Tests LGTM. I'll let @vincent99 comment on regex. Once its good to go, we need to have it squashed down to 1 commit.

**Comment by vincent99** [comment]
LGTM

**Comment by cloudnautique** [comment]
Cool, thanks @Rucknar !!

**Pull request merged**
